Add captive portal functionality, update examples and documentation, resolves #134
s00500/ESPUI pull request #197
Opened 2022-09-19 16:43 UTC by ncmreynolds

I have made a small change to optionally redirect all 404s to the 'root' of the ESP, turning it into a captive portal if acting as a Wi-Fi hotspot and DNS server.

This PR includes changes to the examples and documentation to reflect this. Sorry for the long wait in my producing a complete solution to #134 I got absentminded and forgot about it until I worked on another project with ESPUI.  The existing examples can already act as Wi-Fi hotspot and DNS server so the changes to them are one line.

2022-09-20 08:15 UTC, s00500 commented
hey @ncmreynolds, thanks for the PR
Just one comment: Why make this off by default ? I would argue that we can always have this redirect :-)

2022-09-20 08:27 UTC, ncmreynolds commented
I left it off default because it is probably not very useful when the ESP is acting as a station not a hotspot. Having said that having it on by default most likely wouldn't have any negative effect. Feel free to change this if you wish.

2022-09-20 10:36 UTC, s00500 commented
Please make the change, then lets merge it :-)

2022-09-20 14:34 UTC, ncmreynolds commented
Done (I think, I'm not great with git)

2022-09-20 17:05 UTC, s00500 requested changes
Cool, still got some minor comments, sorry for nitpicking =P

2022-09-20 17:05 UTC, s00500 commented on examples/gui-generic-api/gui-generic-api.ino
> +            ESPUI.captivePortal = true; //Configure ESPUI to be a captive portal only if the ESP is acting as a hotspot
can be removed again

2022-09-20 17:05 UTC, s00500 commented on examples/gui/gui.ino
> +            ESPUI.captivePortal = true; //Configure ESPUI to be a captive portal only if the ESP is acting as a hotspot
can be removed again

2022-09-20 17:05 UTC, s00500 commented on examples/tabbedGui/tabbedGui.ino
> +            ESPUI.captivePortal = true; //Configure ESPUI to be a captive portal only if the ESP is acting as a hotspot
can be removed again

2022-09-20 17:05 UTC, s00500 commented on keywords.txt
> +captivePortal	KEYWORD2
Hm... keyword2 is used for functions... not necessarily for globals

2022-09-20 17:05 UTC, s00500 commented on src/ESPUI.cpp
> +		if(captivePortal == true)
no need to check for == true, just do `if(captivePortal)`

2022-09-21 08:01 UTC, ncmreynolds commented
Suggestions done, also updated the documentation change to reflect this.

2022-09-21 08:06 UTC, s00500 commented
Great, thanks a lot :-)

2022-09-21 08:06 UTC, s00500 approved these changes

2022-09-21 08:06 UTC, merged